language: java
jdk:
  - openjdk8

branches:
  only:
    - master

before_deploy:
  - cd $TRAVIS_BUILD_DIR

deploy:
  - provider: script
    script: ./scripts/run-cd.sh
    on:
      branch: master

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'