language: java
jdk:
  - openjdk8


env:
  - NODE_VERSION="v10.16.0"

before_install:
  - nvm install $NODE_VERSION
  - node ./scripts/setLabelsAsEnv.js $TRAVIS_PULL_REQUEST

branches:
  only:
    - master

before_deploy:
  - cd $TRAVIS_BUILD_DIR

deploy:
  - provider: script
    script: ./scripts/run-cd.sh
    on:
      branch: master

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'